# Generated by Django 3.1.2 on 2021-02-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donar_name', models.CharField(max_length=100)),
                ('donar_blood_group', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('last_donation_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_group.location')),
            ],
        ),
    ]
