# Generated by Django 3.1.2 on 2021-02-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='last_donation_date',
        ),
    ]
